// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2IHnDQS4BHEjxEwEoFSpoHokJherfuKU',
    appId: '1:778230760986:web:e80011fcd56d7b2c7ff3a3',
    messagingSenderId: '778230760986',
    projectId: 'note-a4833',
    authDomain: 'note-a4833.firebaseapp.com',
    storageBucket: 'note-a4833.appspot.com',
    measurementId: 'G-58YC50N162',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnZlUKi7y0BQlAUKJyV8m_M4fUV2gJbyE',
    appId: '1:778230760986:android:82d035f5bbe7f0a77ff3a3',
    messagingSenderId: '778230760986',
    projectId: 'note-a4833',
    storageBucket: 'note-a4833.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt3mw5CyVPF0cKizTYi6pdHNNLHY96FiM',
    appId: '1:778230760986:ios:349120ee2f1df8187ff3a3',
    messagingSenderId: '778230760986',
    projectId: 'note-a4833',
    storageBucket: 'note-a4833.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );
  
}
